### ISSUE TITLE
web ui editor json vs yaml

### ISSUE THREAD

**Issue by hrbu** [ricoberger/sealed-secrets-web#15]
First of all, thanks for implementing and maintaining this project.

----
**My Issue:** Just deployed the current version (`2.2.2`) for evalutation. Just wondering why the ui shows the secrets / sealed secret as `json` (expected `yaml`).

![grafik](https://user-images.githubusercontent.com/10865951/122392916-9b160680-cf74-11eb-80d3-9e6af3d6a1a6.png)

Is this a bug or is there a flag to switch between `yaml` and `json`?

**Comment by ricoberger** [comment]
Hi @hrbu, you can use the `--format yaml` flag to show the secrets in the yaml format.

**Comment by hrbu** [comment]
Perfect. Works as expected. Thanks!
