### ISSUE TITLE
Remove secrets button

### ISSUE THREAD

**Issue by solune** [ricoberger/sealed-secrets-web#3]
Is it easy to remove the secrets button ? 
If you push secrets, select one sealed-secret, push decode : you have the clear password.
For security reasons, I want to disable this, possible ?

**Comment by ricoberger** [comment]
Hi, currently this is not possible. I will have a look at this.

First idea is to introduce an environment variable `DISABLE_LOAD_SECRETS` (or flag) which disables the `loadSecrets()` and `loadSecret()` functions in the fronend. Also the corresponding API endpoints should return a `403` error then.

**Comment by ricoberger** [comment]
Hi @solune, I created a new release [2.1.4](https://github.com/ricoberger/sealed-secrets-web/releases/tag/2.1.4), which includes the changes from #4.

**Comment by solune** [comment]
Already !! thanks a lot
