### ISSUE TITLE
no file worker-json.js

### ISSUE THREAD

**Issue by solune** [ricoberger/sealed-secrets-web#5]
Hi,
I have an error in the browser console:
a8a69659-e9d1-4c68-a776-34f4baca649e:1 Uncaught DOMException: Failed to execute 'importScripts' on 'WorkerGlobalScope': The script at 'https://sealed-secrets-web.myserver.com/static/ace/worker-json.js' failed to load.

This file is doesn't exist
Regards

**Comment by ricoberger** [comment]
Hi, thanks for reporting the issue. This should be fixed in the version [2.1.5](https://github.com/ricoberger/sealed-secrets-web/releases/tag/2.1.5).
